"""add published_at to posts

Revision ID: 83b28527bcf9
Revises: ca711b095193
Create Date: 2026-04-22 00:57:57.615285

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '83b28527bcf9'
down_revision = 'ca711b095193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_logs')
    op.drop_constraint(op.f('uq_cases_owner_actor'), 'cases', type_='unique')
    op.create_index('ix_cases_owner_created_at', 'cases', ['owner_id', 'created_at'], unique=False)
    op.add_column('posts', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    op.drop_column('posts', 'published_at')
    op.drop_index('ix_cases_owner_created_at', table_name='cases')
    op.create_unique_constraint(op.f('uq_cases_owner_actor'), 'cases', ['owner_id', 'actor_id'], postgresql_nulls_not_distinct=False)
    op.create_table('task_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_logs_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('task_logs_pkey'))
    )
    # ### end Alembic commands ###

