"""create_trending_items_table

Revision ID: ca711b095193
Revises: e64f95b72f50
Create Date: 2026-04-18 15:18:38.847324

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ca711b095193'
down_revision = 'e64f95b72f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'trending_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('platform', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('snapshot_date', sa.Date(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('label', sa.String(), nullable=False),
        sa.Column('normalized_label', sa.String(), nullable=False),
        sa.Column('item_type', sa.String(), nullable=True),
        sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('source_url', sa.Text(), nullable=True),
        sa.Column('task_id', sa.Integer(), nullable=True),
        sa.Column('raw_payload', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trending_items_category', 'trending_items', ['category'], unique=False)
    op.create_index('ix_trending_items_id', 'trending_items', ['id'], unique=False)
    op.create_index('ix_trending_items_item_type', 'trending_items', ['item_type'], unique=False)
    op.create_index('ix_trending_items_label', 'trending_items', ['label'], unique=False)
    op.create_index('ix_trending_items_normalized_label', 'trending_items', ['normalized_label'], unique=False)
    op.create_index('ix_trending_items_platform', 'trending_items', ['platform'], unique=False)
    op.create_index('ix_trending_items_rank', 'trending_items', ['rank'], unique=False)
    op.create_index('ix_trending_items_snapshot_date', 'trending_items', ['snapshot_date'], unique=False)
    op.create_index('ix_trending_items_captured_at', 'trending_items', ['captured_at'], unique=False)
    op.create_index('ix_trending_items_task_id', 'trending_items', ['task_id'], unique=False)
    
    # Custom indexes from TrendingItem model
    op.create_index('ix_trending_items_platform_category_date', 'trending_items', ['platform', 'category', 'snapshot_date'], unique=False)
    op.create_index('ix_trending_items_platform_category_date_label', 'trending_items', ['platform', 'category', 'snapshot_date', 'normalized_label'], unique=False)
    op.create_index('uq_trending_items_rank', 'trending_items', ['platform', 'category', 'snapshot_date', 'rank'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_trending_items_rank', table_name='trending_items')
    op.drop_index('ix_trending_items_platform_category_date_label', table_name='trending_items')
    op.drop_index('ix_trending_items_platform_category_date', table_name='trending_items')
    op.drop_index('ix_trending_items_task_id', table_name='trending_items')
    op.drop_index('ix_trending_items_captured_at', table_name='trending_items')
    op.drop_index('ix_trending_items_snapshot_date', table_name='trending_items')
    op.drop_index('ix_trending_items_rank', table_name='trending_items')
    op.drop_index('ix_trending_items_platform', table_name='trending_items')
    op.drop_index('ix_trending_items_normalized_label', table_name='trending_items')
    op.drop_index('ix_trending_items_label', table_name='trending_items')
    op.drop_index('ix_trending_items_item_type', table_name='trending_items')
    op.drop_index('ix_trending_items_id', table_name='trending_items')
    op.drop_index('ix_trending_items_category', table_name='trending_items')
    op.drop_table('trending_items')
    # ### end Alembic commands ###

