"""init schema

Revision ID: d99ff8cb6aa7
Revises: 
Create Date: 2026-02-22 21:04:03.754435

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd99ff8cb6aa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('twitter', 'instagram', 'facebook', 'reddit', 'tiktok', 'other', name='platform_enum'), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle', name='uq_accounts_platform_handle')
    )
    op.create_index(op.f('ix_accounts_created_at'), 'accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_accounts_handle'), 'accounts', ['handle'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_platform'), 'accounts', ['platform'], unique=False)
    op.create_table('coordinated_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('from_label', sa.String(), nullable=False),
    sa.Column('to_label', sa.String(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('member_account_ids', sa.JSON(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coordinated_groups_created_at', 'coordinated_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_coordinated_groups_id'), 'coordinated_groups', ['id'], unique=False)
    op.create_index(op.f('ix_coordinated_groups_week_start'), 'coordinated_groups', ['week_start'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('coordinated_group_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['coordinated_group_id'], ['coordinated_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_account_created_at', 'alerts', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_account_id'), 'alerts', ['account_id'], unique=False)
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_coordinated_group_id'), 'alerts', ['coordinated_group_id'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('drift_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('from_label', sa.String(), nullable=True),
    sa.Column('to_label', sa.String(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drift_scores_account_created_at', 'drift_scores', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_drift_scores_account_id'), 'drift_scores', ['account_id'], unique=False)
    op.create_index('ix_drift_scores_account_week', 'drift_scores', ['account_id', 'week_start'], unique=False)
    op.create_index(op.f('ix_drift_scores_created_at'), 'drift_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_drift_scores_id'), 'drift_scores', ['id'], unique=False)
    op.create_index(op.f('ix_drift_scores_week_start'), 'drift_scores', ['week_start'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('twitter', 'instagram', 'facebook', 'reddit', 'tiktok', 'other', name='platform_enum'), nullable=False),
    sa.Column('platform_post_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_post_id', name='uq_posts_platform_platform_post_id')
    )
    op.create_index(op.f('ix_posts_account_id'), 'posts', ['account_id'], unique=False)
    op.create_index('ix_posts_account_id_created_at', 'posts', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_platform'), 'posts', ['platform'], unique=False)
    op.create_table('post_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=False),
    sa.Column('predicted_label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('topic_vector', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'model_version', name='uq_post_analysis_post_model')
    )
    op.create_index(op.f('ix_post_analysis_created_at'), 'post_analysis', ['created_at'], unique=False)
    op.create_index(op.f('ix_post_analysis_id'), 'post_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_post_analysis_model_version'), 'post_analysis', ['model_version'], unique=False)
    op.create_index(op.f('ix_post_analysis_post_id'), 'post_analysis', ['post_id'], unique=False)
    op.create_index('ix_post_analysis_post_id_created_at', 'post_analysis', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_post_analysis_predicted_label'), 'post_analysis', ['predicted_label'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_analysis_predicted_label'), table_name='post_analysis')
    op.drop_index('ix_post_analysis_post_id_created_at', table_name='post_analysis')
    op.drop_index(op.f('ix_post_analysis_post_id'), table_name='post_analysis')
    op.drop_index(op.f('ix_post_analysis_model_version'), table_name='post_analysis')
    op.drop_index(op.f('ix_post_analysis_id'), table_name='post_analysis')
    op.drop_index(op.f('ix_post_analysis_created_at'), table_name='post_analysis')
    op.drop_table('post_analysis')
    op.drop_index(op.f('ix_posts_platform'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index('ix_posts_account_id_created_at', table_name='posts')
    op.drop_index(op.f('ix_posts_account_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_drift_scores_week_start'), table_name='drift_scores')
    op.drop_index(op.f('ix_drift_scores_id'), table_name='drift_scores')
    op.drop_index(op.f('ix_drift_scores_created_at'), table_name='drift_scores')
    op.drop_index('ix_drift_scores_account_week', table_name='drift_scores')
    op.drop_index(op.f('ix_drift_scores_account_id'), table_name='drift_scores')
    op.drop_index('ix_drift_scores_account_created_at', table_name='drift_scores')
    op.drop_table('drift_scores')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_coordinated_group_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_account_id'), table_name='alerts')
    op.drop_index('ix_alerts_account_created_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_coordinated_groups_week_start'), table_name='coordinated_groups')
    op.drop_index(op.f('ix_coordinated_groups_id'), table_name='coordinated_groups')
    op.drop_index('ix_coordinated_groups_created_at', table_name='coordinated_groups')
    op.drop_table('coordinated_groups')
    op.drop_index(op.f('ix_accounts_platform'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_handle'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_at'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###

